// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZajRS_7LKIEnTCjeWqWccJituenSQCbk',
    appId: '1:236676609411:web:8649f13f0307da680e32b6',
    messagingSenderId: '236676609411',
    projectId: 'loyal-rampart-345111',
    authDomain: 'loyal-rampart-345111.firebaseapp.com',
    storageBucket: 'loyal-rampart-345111.appspot.com',
    measurementId: 'G-5MWD35NSM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZSIzcE8lHxmJyCsnVhZs5smoSnq4d5oE',
    appId: '1:236676609411:android:1c130818a095b8440e32b6',
    messagingSenderId: '236676609411',
    projectId: 'loyal-rampart-345111',
    storageBucket: 'loyal-rampart-345111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQm9Xi0teMQAT0eV-kBGsxS0jhEOsjG2c',
    appId: '1:236676609411:ios:92c33fa26ae8cf1c0e32b6',
    messagingSenderId: '236676609411',
    projectId: 'loyal-rampart-345111',
    storageBucket: 'loyal-rampart-345111.appspot.com',
    iosClientId: '236676609411-p1atr8i4e5gk16aah7qe0m6egg6p5rda.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
